server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/policydb
    username: root
    password: t3stus3r!
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    flyway:
      url: jdbc:mysql://localhost:3306/policydb
      username: root
      password: t3stus3r!

debug: true